[package]
name = "hta_compile"
version = "0.0.1"
authors = ["Harmless_Tech (harmless-tech)"]
edition = "2018"
license = "MIT License - Copyright (c) 2020 Harmless_Tech"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.11"
